version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: hackathon_postgres
    volumes:
      - postgreshackathondata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: unless-stopped
    networks:
      - myhackathon
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - myhackathon

volumes:
  postgreshackathondata:

networks:
  myhackathon:
    driver: bridge